### PR TITLE
Fix hugo deprecation warnings

### PR DESCRIPTION
**Pull request by Staudey**
This fixes two deprectation warnings on (re)building the site

### CODE REVIEW

**Comment by EbonJaeger** [comment]
As a note, the other theming repositories aren't used anymore; both `solus-hugo-theme` and `solbit` were straight copied into this project and modified.

**Comment by Staudey** [comment]
Ah well, that makes things easier then. I thought the theme sync was still working for some reason.

**Comment by EbonJaeger** [comment]
The documentation still says that it is, but it isn't. I discovered this the hard way yesterday lol

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
